export const ErrorStatusCodes = {
  400: 'ClientErrorBadRequest',
  409: 'ClientErrorConflict',
  417: 'ClientErrorExpectationFailed',
  424: 'ClientErrorFailedDependency',
  403: 'ClientErrorForbidden',
  410: 'ClientErrorGone',
  418: 'ClientErrorImATeapot',
  411: 'ClientErrorLengthRequired',
  423: 'ClientErrorLocked',
  440: 'ClientErrorLoginTimeOut',
  405: 'ClientErrorMethodNotAllowed',
  421: 'ClientErrorMisdirectedRequest',
  406: 'ClientErrorNotAcceptable',
  404: 'ClientErrorNotFound',
  413: 'ClientErrorPayloadTooLarge',
  402: 'ClientErrorPaymentRequired',
  412: 'ClientErrorPreconditionFailed',
  428: 'ClientErrorPreconditionRequired',
  407: 'ClientErrorProxyAuthRequired',
  416: 'ClientErrorRangeNotSatisfiable',
  431: 'ClientErrorRequestHeaderFieldsTooLarge',
  408: 'ClientErrorRequestTimeout',
  449: 'ClientErrorRetryWith',
  429: 'ClientErrorTooManyRequests',
  401: 'ClientErrorUnauthorized',
  451: 'ClientErrorUnavailableForLegalReasons',
  422: 'ClientErrorUnprocessableEntity',
  415: 'ClientErrorUnsupportedMediaType',
  426: 'ClientErrorUpgradeRequired',
  414: 'ClientErrorURITooLong',
  502: 'ServerErrorBadGateway',
  509: 'ServerErrorBandwidthLimitExceeded',
  504: 'ServerErrorGatewayTimeout',
  505: 'ServerErrorHTTPVersionNotSupported',
  507: 'ServerErrorInsufficientStorage',
  500: 'ServerErrorInternal',
  508: 'ServerErrorLoopDetected',
  511: 'ServerErrorNetworkAuthRequired',
  510: 'ServerErrorNotExtended',
  501: 'ServerErrorNotImplemented',
  503: 'ServerErrorServiceUnavailable',
  506: 'ServerErrorVariantAlsoNegotiates',
} as const;

export const SuccessStatusCodes = {
  202: 'SuccessAccepted',
  208: 'SuccessAlreadyReported',
  201: 'SuccessCreated',
  229: 'SuccessIMUsed',
  207: 'SuccessMultiStatus',
  204: 'SuccessNoContent',
  203: 'SuccessNonAuthoritativeInfo',
  200: 'SuccessOK',
  206: 'SuccessPartialContent',
  205: 'SuccessResetContent',
} as const;
